catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import home, contacts, product_detail


app_name = CatalogConfig.name

urlpatterns = [
    path("", home, name="home"),
    path("contacts/", contacts, name="contacts"),
    path("product/<int:pk>/", product_detail, name='product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название категории"
    )
    description = models.TextField(
        verbose_name="Описание",
        blank=True,
        null=True,
        help_text="Введите описание категории",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["title"]


class Product(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название продукта"
    )
    description = models.TextField(
        verbose_name="Описание",
        blank=True,
        null=True,
        help_text="Введите описание продукта",
    )
    image = models.ImageField(
        upload_to="images/",
        verbose_name="Изображение",
        blank=True,
        null=True,
        help_text="Загрузите фотографию продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="Категория",
    )
    price = models.FloatField(verbose_name="Цена", help_text="Введите цену продукта")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateField(auto_now=True, verbose_name="Дата изменения")

    def __str__(self):
        return f"{self.title} {self.price}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["title"]

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .models import Product


def home(request: HttpRequest):
    """функция обрабатывает запрос и возвращает html-страницу"""
    if request.method == "GET":
        products = Product.objects.all()
        context = {"products": products}

        return render(request, "home.html", context=context)


def contacts(request):
    """Обрабатываем форму и возвращаем ответ"""
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        return HttpResponse(
            f"Спасибо, {name}, за Ваше сообщение! Наши специалисты скоро свяжутся с Вами по номеру телефона {phone}!"
        )
    return render(request, "contacts.html")


def product_detail(request, pk: int):
    product = get_object_or_404(Product, pk=pk)
    context = {"product": product}
    return render(request, "product_detail.html", context=context)

catalog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Продукты</title>
    {% block title %}{% endblock %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->

</head>
<body>
{% include 'includes/inc_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">ФЕРМЕРСКИЕ ПРОДУКТЫ</h1>
    <p class="lead">доставка за 2 часа</p>
</div>
{% block content %}{% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Продуктовый
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Наши магазины</a></li>
                    <li><a class="text-muted" href="#">Написать нам в соцсетях</a></li>
                    <li><a class="text-muted" href="#">Работа у нас</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Продукты</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">ФЕРМЕРСКИЕ ПРОДУКТЫ</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

catalog/templates/header.html
 <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Продукты ТУТ!</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
 </div>

catalog/templates/header_menu.html
 <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Продукты ТУТ!</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
 </div>

catalog/templates/home.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Главная страница магазина{% endblock %}

{% block 'includes/inc_menu.html' %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
              <div class="card-header">
                  <h4 class="my-0 font-weight-normal text-center">{{ product.title }}</h4>
              </div>
              <img src="{{ product.image | media_filter }}" width="100%" height="250">
              <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Категория продукта: {{ product.category }}</li>
                    <li>- Описание продукта: {{ product.description | truncatechars:100 }}</li>
                </ul>
              <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Купить</a>
                  </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/includes/inc_menu.html
 <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Продукты ТУТ!</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
 </div>

catalog/templates/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %} Продукты {% endblock %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        <div class="col">
          <div class="card shadow-sm">
              <div class="card-header">
                  <h4 class="my-0 font-weight-normal text-center">{{ product.title }}</h4>
              </div>
              <img src="{{ product.image | media_filter }}" width="100%" height="250">
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.price }} рублей</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Дата создания: {{ product.created_at | date:"d M Y"}}</li>
                    <li>- Категория продукта: {{ product.category }}</li>
                    <li>- Описание продукта: {{ product.description | truncatechars:100 }}</li>
                    <li>- Последнее обновление: {{ product.updated_at | date:"d M Y"}}</li>
                </ul>
              <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Купить</a>
                    </div>

                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:home' %}" role="button">Назад</a>
                    </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/products_list.html
{% extends 'base.html' %}
{% block content %}
{% block title %}Главная страница магазина{% endblock %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">{{ product.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-body-secondary">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}